"""Persona render-only pass (SENTINEL-012 Step 11, AC-17).

Synthesis emits the typed, cited finding set **once**. This pass re-presents those *already-established*
facts for a given audience — adapting reading level, tone, and format — and is **structurally** forbidden
from changing them: ``sources`` and ``finding_texts`` are copied verbatim **by code** from the source
artifact, never regenerated by the model. Only :attr:`RenderedArtifact.rendered_text` (the prose) varies
by persona. That is the AC-17 guarantee — two personas over one artifact share byte-identical
facts/sources and differ only in presentation, because the render path never *writes* a fact.

The renderer is a tool-free reasoner (``role=synthesizer`` → gemma-4-26B under tiering): it reasons over
the supplied findings to rephrase them, and has **no tools**, so it cannot fetch new facts (§9.2 — render
must not research). Sovereignty is inherited via ``make_agent``/``resolve_model`` — no Gemini object is
built under ``on_prem_required`` (AC-7/11).
"""

from __future__ import annotations

from dataclasses import dataclass

from google.adk.agents import Agent
from google.adk.agents.run_config import StreamingMode

from sentinel.agent import orchestrator as orch
from sentinel.agent.modes._build import make_agent
from sentinel.artifacts.schemas import Persona, Source
from sentinel.config import SentinelConfig, get_config
from sentinel.memory import finding_texts

RENDERED_KEY = "rendered"          # state/output key the renderer writes its prose under
FINDINGS_KEY = "finding_texts"     # state key the renderer reads (the verbatim facts)


@dataclass(frozen=True)
class RenderedArtifact:
    """A persona-adapted presentation. ``sources``/``finding_texts`` are the artifact's verbatim facts
    (copied by code — the render-only guarantee); ``rendered_text`` is the only persona-driven field."""

    persona: Persona
    rendered_text: str
    sources: list[Source]
    finding_texts: list[str]


def persona_profile(persona: Persona) -> str:
    """A compact, human-readable audience descriptor injected into the renderer's instruction."""
    bits = [
        f"a {persona.name} reader",
        f"reading level: {persona.reading_level}",
        f"tone: {persona.tone}",
        f"format: {persona.format}",
    ]
    if persona.source_policy:
        bits.append(f"source policy: {persona.source_policy}")
    return "; ".join(bits)


def extract_render_facts(artifact) -> tuple[list[Source], list[str]]:
    """The immutable core: the artifact's cited sources + its canonical finding texts, **by code**.

    Reuses the SENTINEL-002 :func:`finding_texts` extractor — the very same facts the run record and
    delta are built from — so a rendered view can never silently diverge from what was researched."""
    sources = list(getattr(artifact, "sources", []) or [])
    return sources, finding_texts(artifact)


def build_persona_renderer(
    persona: Persona,
    cfg: SentinelConfig | None = None,
    backend: str | None = None,
    *,
    cloud_allowed: bool = True,
) -> Agent:
    """Build the render-only reasoner for one persona (tool-free; ``{persona_profile}`` baked in)."""
    cfg = cfg or get_config()
    return make_agent(
        cfg, "persona.renderer", name="persona_renderer",
        output_key=RENDERED_KEY, mode_backend=backend, cloud_allowed=cloud_allowed,
        note_substitutions={"persona_profile": persona_profile(persona)},  # tools omitted → tool-free
    )


def persona_render_seed(artifact) -> dict[str, object]:
    """Seed state for the renderer: the verbatim finding texts under :data:`FINDINGS_KEY`."""
    _sources, texts = extract_render_facts(artifact)
    return {FINDINGS_KEY: texts}


async def render_for_persona(
    artifact,
    persona: Persona,
    *,
    cfg: SentinelConfig | None = None,
    backend: str | None = None,
    cloud_allowed: bool = True,
    trace: list[str] | None = None,
) -> RenderedArtifact:
    """Run the render-only pass for one persona and return a :class:`RenderedArtifact`.

    The model produces ``rendered_text`` only; ``sources``/``finding_texts`` are taken straight from the
    artifact (not from model output) — so the facts are invariant across personas by construction."""
    cfg = cfg or get_config()
    trace = trace if trace is not None else []
    sources, texts = extract_render_facts(artifact)
    agent = build_persona_renderer(persona, cfg, backend, cloud_allowed=cloud_allowed)
    state = await orch.run_step(
        agent, message_text=f"Render the findings for {persona.name}",
        seed_state={FINDINGS_KEY: texts}, streaming=StreamingMode.SSE, trace=trace,
    )
    return RenderedArtifact(
        persona=persona,
        rendered_text=str(state.get(RENDERED_KEY, "")),
        sources=sources,            # verbatim from the artifact — never the model
        finding_texts=texts,        # verbatim from the artifact — never the model
    )
